name: RCF – Päivän tapahtumat

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml python-dateutil

      - name: Post today's RCF events
        env:
          DISCORD_WEBHOOK_URL_EVENTS: ${{ secrets.DISCORD_WEBHOOK_URL_EVENTS }}  # tai käytä samaa uutiskanavan webhookia
        run: |
          python rcf_today_events.py
