name: Arvi Replies

on:
  schedule:
    - cron: "*/20 * * * *"   # 20 minuutin välein
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Arvi reply script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          UUTISKATSAUS_CHANNEL_ID: ${{ secrets.UUTISKATSAUS_CHANNEL_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUMMARY_MODEL: gpt-4o-mini
          ARVI_REPLY_MAXLEN: "280"
          OPENAI_API_BASE: https://api.openai.com/v1
        run: |
          python arvi_replies.py

      - name: Commit arvi_state.json if changed
        run: |
          if [[ -n "$(git status --porcelain arvi_state.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add arvi_state.json
            git commit -m "chore: update arvi_state.json [skip ci]" || true
            git push
          else
            echo "No state changes to commit"
          fi
