name: Blocklist suggester

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Uutisen URL, josta ehdotetaan estolistan avainsanoja"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: blocklist-suggester-${{ github.ref }}
  cancel-in-progress: false

jobs:
  suggest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Aja oma skripti, joka generoi blocklist-ehdokkaat.
      # HUOM: varmista että scripts/suggest_blocklist.py on repossa.
      - name: Run suggester script
        run: |
          python scripts/suggest_blocklist.py "${{ github.event.inputs.url }}"
          echo "----- blocklist_candidates.txt -----"
          test -f blocklist_candidates.txt && cat blocklist_candidates.txt || echo "(no candidates file)"

      # Luo PR automaattisesti erillisestä haarasta päähaaraan
      - name: Create pull request with suggestions
        uses: peter-evans/create-pull-request@v6
        with:
          base: main                       # <-- vaihda jos päähaara ei ole 'main'
          branch: blocklist/candidates-${{ github.run_id }}
          delete-branch: true
          commit-message: "blocklist: add candidates from ${{ github.event.inputs.url }}"
          title: "Blocklist candidates from URL"
          body: |
            Tämä PR lisää/ehdottaa sanoja `blocklist.txt`-tiedostoon.
            - Rivin alussa **# CANDIDATE** = ehdotettu uusi sana.
            - Poista PR:ssä rivit, joita ET halua blocklistalle.
            - (Valinnaista) Poista `# CANDIDATE` niiden rivien edestä, jotka hyväksyt.
            Kun valmis → **Merge pull request**.

          add-paths: |
            blocklist.txt
            blocklist_candidates.txt
