name: RCF – Päivän tapahtumat

on:
  schedule:
    - cron: "0 4 * * *"    # 07:00 Europe/Helsinki (cron on aina UTC)
  workflow_dispatch:        # -> näyttää "Run workflow" -napin

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml python-dateutil

      - name: Post today's RCF events
        env:
          # jos käytät samaa kanavaa kuin uutisissa, tätä ei tarvitse määritellä:
          # DISCORD_WEBHOOK_URL_EVENTS putoaa automaattisesti DISCORD_WEBHOOK_URL:iin
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python rcf_today_events.py
