name: RCF Zwift & MyWhoosh uutiset
on:
  schedule:
    - cron: "*/30 * * * *"  # 30 min välein
  workflow_dispatch:

permissions:
  contents: write  # sallii seen.jsonin commitoinnin

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetcher
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python fetch_and_post.py

      - name: Commit seen.json if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add seen.json
            git commit -m "chore: update seen.json [skip ci]" || true
            git push
          else
            echo "No changes to commit"
          fi
