name: Weekly Events Digest

on:
  schedule:
    - cron: "0 6 * * 1"    # 06:00 UTC = 09:00 Helsinki maanantaisin
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      GUILD_ID: ${{ secrets.GUILD_ID }}
      TARGET_CHANNEL_ID: ${{ secrets.TARGET_CHANNEL_ID }}
      CAL_CHANNEL_IDS: ${{ secrets.CAL_CHANNEL_IDS }}
      TZ: ${{ secrets.TZ }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install discord.py
      - run: python weekly_events_digest.py
