name: Weekly Events Digest (ICS)

on:
  schedule:
    - cron: "0 5 * * 1"   # 05:00 UTC = 08:00 Helsinki maanantaisin
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      TARGET_CHANNEL_ID: ${{ secrets.TARGET_CHANNEL_ID }}
      SESH_ICS_URL: ${{ secrets.SESH_ICS_URL }}
      TZ: ${{ secrets.TZ }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install discord.py requests icalendar recurring-ical-events
      - run: python weekly_events_from_ics.py
